In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
health_2018 = pd.read_csv("health_2018_merged.csv")
health_2018 = health_2018[["Year","GeographicLevel","State","City","Category","Measure","Data_Type","Data_Value","Low_Confidence_Limit","High_Confidence_Limit","Population","Tract GeoLocation","CityFIPS","TractFIPS","Restaurant Name","Zip Code","Restaurant Latitude","Restaurant Longitude"]]
health_2018.head()

,Year,GeographicLevel,State,City,Category,Measure,Data_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,Population,Tract GeoLocation,CityFIPS,TractFIPS,Restaurant Name,Zip Code,Restaurant Latitude,Restaurant Longitude
0,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,5.9,5.4,6.4,3257,"(33.5213873564, -86.7490031289)",107000.0,1073002306,Hardee's,35212,33.5470,-86.7579
1,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,5.9,5.4,6.4,3257,"(33.5213873564, -86.7490031289)",107000.0,1073002306,McDonald's,35212,33.5435,-86.7486
2,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,7.8,7.2,8.3,3629,"(33.5260748309, -86.7830315488)",107000.0,1073002400,Hardee's,35212,33.5470,-86.7579
3,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,7.8,7.2,8.3,3629,"(33.5260748309, -86.7830315488)",107000.0,1073002400,McDonald's,35212,33.5435,-86.7486
4,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,8.3,7.7,9.0,2735,"(33.5428208686, -86.752433978)",107000.0,1073000300,Hardee's,35212,33.5470,-86.7579

In [56]:
tract_restaurant_counts = health_2018.groupby("TractFIPS")["Restaurant Name"].count().sort_values(ascending=False).reset_index()
tract_restaurant_counts

      TractFIPS  Restaurant Name
0    1073014302               40
1    1117030303               38
2    1125012405               26
3    1125012403               26
4    1125011901               26
5    1089000702               25
6    1089001402               25
7    1117030304               24
8    1089003000               24
9    1073012907               24
10   1117030305               23
11   1101003302               22
12   1097003704               22
13   1101005901               22
14   1073014413               22
15   1097006402               21
16   1073014203               21
17   1097003405               21
18   1097003404               21
19   1125012600               20
20   1125012000               20
21   1125011200               20
22   1089010901               20
23   1125011600               20
24   1125010500               20
25   1101002201               20
26   1101002100               20
27   1101005101               19
28   1089001200               19
29   1073000100               19
..          ...              ...
354  1089002200                2
355  1073002305                2
356  1089002300                2
357  1089002400                2
358  1097003000                2
359  1073000300                2
360  1097001901                2
361  2020001601                2
362  1073013100                2
363  1097000500                2
364  1073005701                2
365  1097007400                2
366  1073005200                2
367  1073005103                2
368  1073005101                2
369  1097001502                2
370  1097001002                2
371  1073005702                2
372  1073004000                2
373  1125010203                2
374  1097001800                2
375  1073004702                1
376  1073010801                1
377  1125010406                1
378  1097001100                1
379  1097000200                1
380  1125010405                1
381  1073012500                1
382  1125010101                1
383  1073004800                1

[384 rows x 2 columns]

In [57]:
tract_disease_prev = health_2018.groupby("TractFIPS")["Data_Value"].unique().reset_index()
tract_disease_prev

      TractFIPS Data_Value
0    1073000100      [8.1]
1    1073000300      [8.3]
2    1073000400      [8.0]
3    1073000500     [10.1]
4    1073000700     [11.4]
5    1073000800     [10.3]
6    1073001100      [7.7]
7    1073001200      [9.0]
8    1073001400      [9.7]
9    1073001500      [9.9]
10   1073001600     [10.7]
11   1073001902      [8.9]
12   1073002000      [9.1]
13   1073002100      [7.7]
14   1073002200      [7.6]
15   1073002303      [8.2]
16   1073002305      [4.3]
17   1073002306      [5.9]
18   1073002400      [7.8]
19   1073002700      [7.3]
20   1073002900     [11.1]
21   1073003001      [5.8]
22   1073003002     [11.1]
23   1073003100      [8.0]
24   1073003200     [11.2]
25   1073003300     [10.4]
26   1073003400      [9.0]
27   1073003600      [7.5]
28   1073003700      [7.7]
29   1073003802      [7.1]
..          ...        ...
354  2020001400      [4.8]
355  2020001500      [6.1]
356  2020001601      [4.5]
357  2020001602      [4.5]
358  2020001701      [4.5]
359  2020001702      [4.8]
360  2020001731      [5.5]
361  2020001732      [4.1]
362  2020001801      [3.4]
363  2020001802      [5.2]
364  2020001900      [5.2]
365  2020002000      [5.7]
366  2020002100      [4.3]
367  2020002201      [4.5]
368  2020002202      [5.0]
369  2020002301      [4.3]
370  2020002302      [4.4]
371  2020002303      [3.8]
372  2020002400      [5.3]
373  2020002501      [4.5]
374  2020002502      [4.0]
375  2020002601      [4.0]
376  2020002602      [3.7]
377  2020002603      [3.5]
378  2020002702      [4.3]
379  2020002711      [4.6]
380  2020002712      [4.4]
381  2020002811      [3.8]
382  2020002812      [4.4]
383  2020002813      [5.2]

[384 rows x 2 columns]

In [58]:
disease_density = pd.merge(tract_restaurant_counts,tract_disease_prev, on="TractFIPS")
disease_density

      TractFIPS  Restaurant Name  Data_Value
0    1073014302               40  [3.3, 3.9]
1    1117030303               38  [2.0, 6.7]
2    1125012405               26       [4.9]
3    1125012403               26       [3.3]
4    1125011901               26       [4.2]
5    1089000702               25      [11.1]
6    1089001402               25       [4.9]
7    1117030304               24       [5.8]
8    1089003000               24      [11.8]
9    1073012907               24       [5.8]
10   1117030305               23       [5.9]
11   1101003302               22       [6.1]
12   1097003704               22       [6.1]
13   1101005901               22       [7.7]
14   1073014413               22  [3.4, 4.8]
15   1097006402               21       [8.1]
16   1073014203               21       [4.9]
17   1097003405               21       [8.2]
18   1097003404               21       [7.3]
19   1125012600               20       [3.7]
20   1125012000               20       [3.4]
21   1125011200               20       [1.6]
22   1089010901               20       [4.5]
23   1125011600               20       [7.2]
24   1125010500               20       [5.4]
25   1101002201               20       [9.2]
26   1101002100               20       [7.0]
27   1101005101               19       [4.2]
28   1089001200               19       [9.4]
29   1073000100               19       [8.1]
..          ...              ...         ...
354  1089002200                2       [9.1]
355  1073002305                2       [4.3]
356  1089002300                2       [8.7]
357  1089002400                2       [6.9]
358  1097003000                2       [7.6]
359  1073000300                2       [8.3]
360  1097001901                2       [9.7]
361  2020001601                2       [4.5]
362  1073013100                2      [10.3]
363  1097000500                2      [11.0]
364  1073005701                2       [8.2]
365  1097007400                2       [7.6]
366  1073005200                2       [9.0]
367  1073005103                2      [10.3]
368  1073005101                2       [9.9]
369  1097001502                2       [8.5]
370  1097001002                2       [6.4]
371  1073005702                2      [10.0]
372  1073004000                2       [9.8]
373  1125010203                2       [3.9]
374  1097001800                2       [8.9]
375  1073004702                1       [6.0]
376  1073010801                1       [4.7]
377  1125010406                1       [6.6]
378  1097001100                1      [10.9]
379  1097000200                1      [10.7]
380  1125010405                1       [5.4]
381  1073012500                1      [10.0]
382  1125010101                1       [4.8]
383  1073004800                1       [7.2]

[384 rows x 3 columns]

In [59]:
what = health_2018[health_2018["TractFIPS"] == 1073014302]
what

,Year,GeographicLevel,State,City,Category,Measure,Data_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,Population,Tract GeoLocation,CityFIPS,TractFIPS,Restaurant Name,Zip Code,Restaurant Latitude,Restaurant Longitude
510,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35211,33.5000,-86.8471
511,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35211,33.4804,-86.8414
512,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35211,33.5000,-86.8471
513,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35211,33.4804,-86.8414
617,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,Pizza Hut,35020,33.3933,-86.9690
618,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,KFC,35020,33.4059,-86.9617
619,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35020,33.4278,-86.9527
620,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35020,33.3959,-86.9693
621,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,Taco Bell,35020,33.3322,-86.9139
622,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,Taco Bell,35020,33.3891,-86.9723
623,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,Pizza Hut,35020,33.3933,-86.9690
624,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,KFC,35020,33.4059,-86.9617
625,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35020,33.4278,-86.9527
626,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35020,33.3959,-86.9693
627,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,Taco Bell,35020,33.3322,-86.9139
628,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,Taco Bell,35020,33.3891,-86.9723
817,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,Pizza Hut,35244,33.3509,-86.8655
818,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,Pizza Hut,35244,33.3834,-86.7402
819,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35244,33.3800,-86.8049
820,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35244,33.3801,-86.8065
821,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35244,33.3837,-86.7400
822,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35244,33.3634,-86.8262
823,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,Taco Bell,35244,33.3687,-86.7933
824,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,Taco Bell,35244,33.3789,-86.8085
825,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,Wendy's,35244,33.3726,-86.8008
826,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,Pizza Hut,35244,33.3509,-86.8655
827,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,Pizza Hut,35244,33.3834,-86.7402
828,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35244,33.3800,-86.8049
829,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35244,33.3801,-86.8065
830,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35244,33.3837,-86.7400
831,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35244,33.3634,-86.8262
832,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,Taco Bell,35244,33.3687,-86.7933
833,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,Taco Bell,35244,33.3789,-86.8085
834,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,Wendy's,35244,33.3726,-86.8008
979,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,Burger King,35022,33.3605,-86.9988
980,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35022,33.3371,-86.9222
981,2016,Census Tract,Alabama,Birmingham,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.3,3.0,3.5,2778,"(33.4244658829, -86.8841474217)",107000.0,1073014302,McDonald's,35022,33.3626,-86.9986
982,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,Burger King,35022,33.3605,-86.9988
983,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35022,33.3371,-86.9222
984,2016,Census Tract,Alabama,Hoover,Coronary Heart Disease,Coronary heart disease among adults aged >=18 ...,Crude prevalence,3.9,3.5,4.4,1636,"(33.3923792867, -86.8833755105)",135896.0,1073014302,McDonald's,35022,33.3626,-86.9986